"""empty message

Revision ID: 5421e7a49b3e
Revises: 
Create Date: 2023-09-13 11:59:47.427565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5421e7a49b3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GRBAlert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('RA', sa.Float(), nullable=True),
    sa.Column('DEC', sa.Float(), nullable=True),
    sa.Column('TimeInstant', sa.DateTime(), nullable=True),
    sa.Column('FullContents', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GWAlert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Packet_Type', sa.Integer(), nullable=True),
    sa.Column('internal', sa.Integer(), nullable=True),
    sa.Column('Pkt_Ser_Num', sa.Integer(), nullable=True),
    sa.Column('GraceID', sa.String(length=45), nullable=True),
    sa.Column('AlertType', sa.String(length=45), nullable=True),
    sa.Column('HardwareInj', sa.Integer(), nullable=True),
    sa.Column('OpenAlert', sa.Integer(), nullable=True),
    sa.Column('EventPage', sa.String(length=200), nullable=True),
    sa.Column('Instruments', sa.String(length=50), nullable=True),
    sa.Column('FAR', sa.Float(), nullable=True),
    sa.Column('Group', sa.String(length=45), nullable=True),
    sa.Column('Pipeline', sa.String(length=45), nullable=True),
    sa.Column('Search', sa.String(length=45), nullable=True),
    sa.Column('skymap_fits', sa.String(length=200), nullable=True),
    sa.Column('BNS', sa.Float(), nullable=True),
    sa.Column('NSBH', sa.Float(), nullable=True),
    sa.Column('BBH', sa.Float(), nullable=True),
    sa.Column('Terrestrial', sa.Float(), nullable=True),
    sa.Column('HasNS', sa.Float(), nullable=True),
    sa.Column('HasRemnant', sa.Float(), nullable=True),
    sa.Column('HasMassGap', sa.Float(), nullable=True),
    sa.Column('TimeInstant', sa.DateTime(), nullable=True),
    sa.Column('External_GCN_Notice_Id', sa.String(length=200), nullable=True),
    sa.Column('External_Ivorn', sa.String(length=200), nullable=True),
    sa.Column('External_Observatory', sa.String(length=200), nullable=True),
    sa.Column('External_Search', sa.String(length=45), nullable=True),
    sa.Column('Time_Difference', sa.Float(), nullable=True),
    sa.Column('Time_Coincidence_FAR', sa.Float(), nullable=True),
    sa.Column('Time_Sky_Position_Coincidence_FAR', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SNAlert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Packet_Type', sa.Integer(), nullable=True),
    sa.Column('Pkt_Ser_Num', sa.Integer(), nullable=True),
    sa.Column('Trigger_Number', sa.Integer(), nullable=True),
    sa.Column('Pkt_TJD', sa.Integer(), nullable=True),
    sa.Column('Pkt_SOD', sa.Float(), nullable=True),
    sa.Column('Energy_Limit', sa.Float(), nullable=True),
    sa.Column('Duration', sa.Float(), nullable=True),
    sa.Column('Src_Error68', sa.Float(), nullable=True),
    sa.Column('Src_Error90', sa.Float(), nullable=True),
    sa.Column('Src_Error95', sa.Float(), nullable=True),
    sa.Column('N_Events', sa.Integer(), nullable=True),
    sa.Column('Min_Distance', sa.Float(), nullable=True),
    sa.Column('Max_Distance', sa.Float(), nullable=True),
    sa.Column('Discovery_date', sa.Integer(), nullable=True),
    sa.Column('Discovery_time', sa.Integer(), nullable=True),
    sa.Column('RA', sa.Float(), nullable=True),
    sa.Column('DEC', sa.Float(), nullable=True),
    sa.Column('TimeInstant', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogue_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=300), nullable=False),
    sa.Column('available_field', sa.String(length=300), nullable=True),
    sa.Column('position_field', sa.String(length=300), nullable=True),
    sa.Column('wavelength', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.String(length=50), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('article_type', sa.Enum('NEWS', 'FLATPAGE', name='articletype'), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=255), nullable=True),
    sa.Column('top_image_path', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('ontop', sa.Boolean(), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=True),
    sa.Column('upcoming_event', sa.Boolean(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('editor_id', sa.Integer(), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_article_article_type'), 'cms_article', ['article_type'], unique=False)
    op.create_index(op.f('ix_cms_article_title'), 'cms_article', ['title'], unique=False)
    op.create_table('cms_carousel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_carousel_title'), 'cms_carousel', ['title'], unique=False)
    op.create_table('cms_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('category_type', sa.Enum('NEWS', 'FLATPAGE', name='articletype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_category_category_type'), 'cms_category', ['category_type'], unique=False)
    op.create_index(op.f('ix_cms_category_name'), 'cms_category', ['name'], unique=False)
    op.create_table('login_tries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('next', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_tries_email'), 'login_tries', ['email'], unique=False)
    op.create_table('pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oss_path', sa.String(length=100), nullable=True),
    sa.Column('process_time', sa.DateTime(), nullable=False),
    sa.Column('pipeline_id', sa.String(length=100), nullable=True),
    sa.Column('obs_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('associate_science_team_application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referer_name', sa.String(length=30), nullable=False),
    sa.Column('referer_given_name', sa.String(length=30), nullable=False),
    sa.Column('referer_family_name', sa.String(length=30), nullable=False),
    sa.Column('name1', sa.String(length=30), nullable=False),
    sa.Column('given_name1', sa.String(length=30), nullable=False),
    sa.Column('family_name1', sa.String(length=30), nullable=False),
    sa.Column('title1', sa.String(length=30), nullable=False),
    sa.Column('institute1', sa.String(length=100), nullable=False),
    sa.Column('email1', sa.String(length=254), nullable=False),
    sa.Column('agntde1', sa.Boolean(), nullable=True),
    sa.Column('fet1', sa.Boolean(), nullable=True),
    sa.Column('mma1', sa.Boolean(), nullable=True),
    sa.Column('cso1', sa.Boolean(), nullable=True),
    sa.Column('os1', sa.Boolean(), nullable=True),
    sa.Column('fuoa1', sa.Boolean(), nullable=True),
    sa.Column('intro1', sa.String(length=500), nullable=False),
    sa.Column('name2', sa.String(length=30), nullable=True),
    sa.Column('given_name2', sa.String(length=30), nullable=True),
    sa.Column('family_name2', sa.String(length=30), nullable=True),
    sa.Column('title2', sa.String(length=30), nullable=True),
    sa.Column('institute2', sa.String(length=100), nullable=True),
    sa.Column('email2', sa.String(length=254), nullable=True),
    sa.Column('agntde2', sa.Boolean(), nullable=True),
    sa.Column('fet2', sa.Boolean(), nullable=True),
    sa.Column('mma2', sa.Boolean(), nullable=True),
    sa.Column('cso2', sa.Boolean(), nullable=True),
    sa.Column('os2', sa.Boolean(), nullable=True),
    sa.Column('fuoa2', sa.Boolean(), nullable=True),
    sa.Column('intro2', sa.String(length=500), nullable=True),
    sa.Column('name3', sa.String(length=30), nullable=True),
    sa.Column('given_name3', sa.String(length=30), nullable=True),
    sa.Column('family_name3', sa.String(length=30), nullable=True),
    sa.Column('title3', sa.String(length=30), nullable=True),
    sa.Column('institute3', sa.String(length=100), nullable=True),
    sa.Column('email3', sa.String(length=254), nullable=True),
    sa.Column('agntde3', sa.Boolean(), nullable=True),
    sa.Column('fet3', sa.Boolean(), nullable=True),
    sa.Column('mma3', sa.Boolean(), nullable=True),
    sa.Column('cso3', sa.Boolean(), nullable=True),
    sa.Column('os3', sa.Boolean(), nullable=True),
    sa.Column('fuoa3', sa.Boolean(), nullable=True),
    sa.Column('intro3', sa.String(length=500), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('accept', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_associate_science_team_application_referer_name'), 'associate_science_team_application', ['referer_name'], unique=False, schema='tdic')
    op.create_table('atel_fullcontent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atel_id', sa.Integer(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('backreflist', sa.String(length=2000), nullable=True),
    sa.Column('email', sa.String(length=450), nullable=True),
    sa.Column('reflist', sa.String(length=450), nullable=True),
    sa.Column('tags', sa.String(length=450), nullable=True),
    sa.Column('title', sa.String(length=450), nullable=True),
    sa.Column('ateltype', sa.String(length=500), nullable=True),
    sa.Column('datepublished', sa.DateTime(), nullable=True),
    sa.Column('usertext', sa.Text(), nullable=True),
    sa.Column('dateparsed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atel_id'),
    schema='tdic'
    )
    op.create_table('friend_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_zh', sa.String(length=300), nullable=True),
    sa.Column('name_en', sa.String(length=300), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('logo_url', sa.String(length=300), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_friend_link_logo_url'), 'friend_link', ['logo_url'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_friend_link_name_en'), 'friend_link', ['name_en'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_friend_link_name_zh'), 'friend_link', ['name_zh'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_friend_link_url'), 'friend_link', ['url'], unique=False, schema='tdic')
    op.create_table('login_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=60), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('signtime', sa.DateTime(), nullable=True),
    sa.Column('expire', sa.DateTime(), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_table('paper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('journal', sa.String(length=500), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('pages', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('file_save_name', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_paper_user_id'), 'paper', ['user_id'], unique=False, schema='tdic')
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='tdic'
    )
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_season_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=64), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('preset_too_no', sa.String(length=20), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('can_submit_again', sa.Boolean(), nullable=True),
    sa.Column('proposal_number', sa.String(length=64), nullable=True),
    sa.Column('resubmission', sa.Boolean(), nullable=True),
    sa.Column('resubmission_numbers', sa.Text(), nullable=True),
    sa.Column('stp', sa.String(length=10), nullable=True),
    sa.Column('total_time_request', sa.Float(), nullable=True),
    sa.Column('total_time_assigned', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=6), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('proposal_title', sa.Text(), nullable=True),
    sa.Column('proposal_abstract', sa.Text(), nullable=True),
    sa.Column('content_status', sa.Boolean(), nullable=True),
    sa.Column('equipment_status', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('identification', sa.String(length=256), nullable=True),
    sa.Column('submit_status', sa.Boolean(), nullable=True),
    sa.Column('technical_review_finished', sa.Boolean(), nullable=True),
    sa.Column('scientific_review_finished', sa.Boolean(), nullable=True),
    sa.Column('final_review_comment', sa.Text(), nullable=True),
    sa.Column('final_review_comment_finished', sa.Boolean(), nullable=True),
    sa.Column('open_to_pi', sa.Boolean(), nullable=True),
    sa.Column('force_open_to_pi', sa.Boolean(), nullable=True),
    sa.Column('project_created', sa.Boolean(), nullable=True),
    sa.Column('pid', sa.String(length=64), nullable=True),
    sa.Column('project_source_created', sa.Boolean(), nullable=True),
    sa.Column('science_case_storage_name', sa.String(length=256), nullable=True),
    sa.Column('science_case_display_name', sa.String(length=256), nullable=True),
    sa.Column('science_case_upload_status', sa.Boolean(), nullable=True),
    sa.Column('lock', sa.Boolean(), nullable=True),
    sa.Column('type1', sa.Enum('STP', 'GO', 'TOOMM', 'TOO', name='proposaltype1'), nullable=True),
    sa.Column('type2', sa.Enum('NonToo', 'AnticipateToO', 'Calibration', 'HighestUrgencyToO', 'HighUrgencyToO', 'MediumUrgencyToO', 'LowUrgencyToO', 'TooMM', 'GuestObserver', 'SYToo', name='proposaltype2'), nullable=True),
    sa.Column('obs_type', sa.String(length=50), nullable=True),
    sa.Column('ant_too_trig_criteria', sa.Text(), nullable=True),
    sa.Column('other_remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_proposal_code'), 'proposal', ['code'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_expiration'), 'proposal', ['expiration'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_identification'), 'proposal', ['identification'], unique=True, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_pid'), 'proposal', ['pid'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_priority'), 'proposal', ['priority'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_proposal_number'), 'proposal', ['proposal_number'], unique=True, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_proposal_season_id'), 'proposal', ['proposal_season_id'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_season'), 'proposal', ['season'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_stp'), 'proposal', ['stp'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_type1'), 'proposal', ['type1'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_type2'), 'proposal', ['type2'], unique=False, schema='tdic')
    op.create_table('proposal_season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=64), nullable=True),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('season_type', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('create_email', sa.String(length=256), nullable=True),
    sa.Column('review_deadline', sa.DateTime(), nullable=True),
    sa.Column('project_expiration', sa.DateTime(), nullable=True),
    sa.Column('inner_expert_weight', sa.Float(), nullable=True),
    sa.Column('outer_expert_weight', sa.Float(), nullable=True),
    sa.Column('identification', sa.String(length=256), nullable=True),
    sa.Column('open_to_pi_final_review_comment', sa.Boolean(), nullable=True),
    sa.Column('open_to_pi_technical_review_comment', sa.Boolean(), nullable=True),
    sa.Column('open_to_pi_scientific_review_comment', sa.Boolean(), nullable=True),
    sa.Column('announcement_link', sa.Text(), nullable=True),
    sa.Column('help_link', sa.Text(), nullable=True),
    sa.Column('parameter_link', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_proposal_season_expiration'), 'proposal_season', ['expiration'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_season_identification'), 'proposal_season', ['identification'], unique=True, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_season_open_date'), 'proposal_season', ['open_date'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_season_review_deadline'), 'proposal_season', ['review_deadline'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_season_season'), 'proposal_season', ['season'], unique=False, schema='tdic')
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='tdic'
    )
    op.create_table('science_team_application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('institute', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('reseach_type', sa.String(length=200), nullable=False),
    sa.Column('observation_research', sa.String(length=200), nullable=False),
    sa.Column('agntde', sa.Boolean(), nullable=True),
    sa.Column('agntde_paper', sa.String(length=500), nullable=True),
    sa.Column('fet', sa.Boolean(), nullable=True),
    sa.Column('fet_paper', sa.String(length=500), nullable=True),
    sa.Column('mma', sa.Boolean(), nullable=True),
    sa.Column('mma_paper', sa.String(length=500), nullable=True),
    sa.Column('cso', sa.Boolean(), nullable=True),
    sa.Column('cso_paper', sa.String(length=500), nullable=True),
    sa.Column('os', sa.Boolean(), nullable=True),
    sa.Column('os_type', sa.String(length=100), nullable=True),
    sa.Column('os_paper', sa.String(length=500), nullable=True),
    sa.Column('fuoa', sa.Boolean(), nullable=True),
    sa.Column('fuoa_paper', sa.String(length=500), nullable=True),
    sa.Column('fuoa_intro', sa.String(length=500), nullable=True),
    sa.Column('application_file', sa.String(length=500), nullable=True),
    sa.Column('commitment_file', sa.String(length=500), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('accept', sa.Boolean(), nullable=True),
    sa.Column('be_chair', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_science_team_application_address'), 'science_team_application', ['address'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_application_email'), 'science_team_application', ['email'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_application_institute'), 'science_team_application', ['institute'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_application_name'), 'science_team_application', ['name'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_application_observation_research'), 'science_team_application', ['observation_research'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_application_reseach_type'), 'science_team_application', ['reseach_type'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_application_telephone'), 'science_team_application', ['telephone'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_application_title'), 'science_team_application', ['title'], unique=False, schema='tdic')
    op.create_table('science_team_survey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('institute', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('emaal', sa.String(length=254), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('reseach_type', sa.String(length=200), nullable=False),
    sa.Column('observation_research', sa.String(length=200), nullable=False),
    sa.Column('how_to_analyze_data', sa.String(length=200), nullable=False),
    sa.Column('expected_joint_doctoral_candidate', sa.String(length=20), nullable=True),
    sa.Column('expected_joint_postdoctoral', sa.String(length=20), nullable=True),
    sa.Column('agntde', sa.Boolean(), nullable=True),
    sa.Column('agntde_paper', sa.String(length=500), nullable=True),
    sa.Column('fet', sa.Boolean(), nullable=True),
    sa.Column('fet_paper', sa.String(length=500), nellable=True),
    sa.Column('mma', sa.Boolean(), nullable=True),
    sa.Column('mma_paper', sa.String(length=500), nullable=True),
    sa.Column('cso', sa.Boolean(), nullable=True),
    sa.Column('cso_paper', sa.String(length=500), nullable=True),
    sa.Column('os', sa.Boolean(), nullable=True),
    sa.Column('os_type', sa.String(length=100), nullable=True),
    sa.Column('os_paper', sa.String(length=500), nullable=True),
    sa.Column('fuoa', sa.Boolean(), nullable=True),
    sa.Column('fuoa_paper', sa.String(length=500), nullable=True),
    sa.Column('fuoa_intro', sa.String(length=500), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('accept', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_science_team_survey_address'), 'science_team_survey', ['address'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_survey_email'), 'science_team_survey', ['email'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_survey_how_to_analyze_data'), 'science_team_survey', ['how_to_analyze_data'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_survey_institute'), 'science_team_survey', ['institute'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_survey_name'), 'science_team_survey', ['name'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_survey_observation_research'), 'science_team_survey', ['observation_research'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_survey_reseach_type'), 'science_team_survey', ['reseach_type'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_survey_telephone'), 'science_team_survey', ['telephone'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_science_team_survey_title'), 'science_team_survey', ['title'], unique=False, schema='tdic')
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TDE', 'GRB', 'SGRB', 'LL_LGRBs', 'HL_LGRBs', 'SBO', 'HZ_GRBs', 'AGN', 'XRB', 'CV', 'STAR', 'ULX', 'MAGNETAR', 'SNR', 'GALAXY', 'UNKNOWN', 'OTHER', name='sourcetype'), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('ra', sa.Float(), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('pos_err', sa.Float(), nullable=False),
    sa.Column('absflux', sa.Float(), nullable=True),
    sa.Column('redshift', sa.Float(), nullable=True),
    sa.Column('luminosity', sa.Float(), nullable=True),
    sa.Column('counts', sa.Float(), nullable=True),
    sa.Column('snr', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('light_curve', sa.String(length=255), nullable=True),
    sa.Column('spectrum', sa.String(length=255), nullable=True),
    sa.Column('latest_net_rate', sa.Float(), nullable=True),
    sa.Column('transient_candidate', sa.Boolean(), nullable=True),
    sa.Column('xray_counterpart', sa.Text(), nullable=True),
    sa.Column('other_counterpart', sa.Text(), nullable=True),
    sa.Column('src_type', sa.String(length=20), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('simbad_name', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('ref_flux', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_source_type'), 'source', ['type'], unique=False, schema='tdic')
    op.create_table('source_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='tdic'
    )
    op.create_table('sql_alchemy_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('command', sa.String(length=500), nullable=True),
    sa.Column('pid', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('tables', sa.String(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_table('sys_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('title_zh', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tdic.sys_menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_sys_menu_order'), 'sys_menu', ['order'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_sys_menu_title_en'), 'sys_menu', ['title_en'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_sys_menu_title_zh'), 'sys_menu', ['title_zh'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_sys_menu_url'), 'sys_menu', ['url'], unique=False, schema='tdic')
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_github', sa.Integer(), nullable=True),
    sa.Column('id_weibo', sa.Integer(), nullable=True),
    sa.Column('id_qq', sa.Integer(), nullable=True),
    sa.Column('id_wechat', sa.Integer(), nullable=True),
    sa.Column('id_cstnet', sa.Integer(), nullable=True),
    sa.Column('id_escience', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('avatar_s', sa.String(length=64), nullable=True),
    sa.Column('avatar_m', sa.String(length=64), nullable=True),
    sa.Column('avatar_l', sa.String(length=64), nullable=True),
    sa.Column('avatar_raw', sa.String(length=64), nullable=True),
    sa.Column('locale', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('institution', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('is_domestic', sa.Boolean(), nullable=True),
    sa.Column('user_group', sa.String(length=20), nullable=True),
    sa.Column('affiliation', sa.String(length=200), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('expertise', sa.String(length=200), nullable=True),
    sa.Column('research_field', sa.String(length=200), nullable=True),
    sa.Column('research_statement', sa.String(length=500), nullable=True),
    sa.Column('publication', sa.Text(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('accepted_policy', sa.Boolean(), nullable=True),
    sa.Column('display_personal_info', sa.Boolean(), nullable=True),
    sa.Column('expert_type', sa.String(length=10), nullable=True),
    sa.Column('allowed_api', sa.Boolean(), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('receive_system_email', sa.Boolean(), nullable=True),
    sa.Column('receive_comment_notification', sa.Boolean(), nullable=True),
    sa.Column('receive_comment_email', sa.Boolean(), nullable=True),
    sa.Column('receive_observation_status_notification', sa.Boolean(), nullable=True),
    sa.Column('receive_observation_status_email', sa.Boolean(), nullable=True),
    sa.Column('receive_datacenter_status_notification', sa.Boolean(), nullable=True),
    sa.Column('receive_datacenter_status_email', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_user_email'), 'user', ['email'], unique=True, schema='tdic')
    op.create_index(op.f('ix_tdic_user_id_cstnet'), 'user', ['id_cstnet'], unique=True, schema='tdic')
    op.create_index(op.f('ix_tdic_user_id_escience'), 'user', ['id_escience'], unique=True, schema='tdic')
    op.create_index(op.f('ix_tdic_user_id_github'), 'user', ['id_github'], unique=True, schema='tdic')
    op.create_index(op.f('ix_tdic_user_id_qq'), 'user', ['id_qq'], unique=True, schema='tdic')
    op.create_index(op.f('ix_tdic_user_id_wechat'), 'user', ['id_wechat'], unique=True, schema='tdic')
    op.create_index(op.f('ix_tdic_user_id_weibo'), 'user', ['id_weibo'], unique=True, schema='tdic')
    op.create_table('user_modify_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('institution', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('user_group', sa.String(length=20), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approve_timestamp', sa.DateTime(), nullable=True),
    sa.Column('affiliation', sa.String(length=200), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('expertise', sa.String(length=200), nullable=True),
    sa.Column('research_field', sa.String(length=200), nullable=True),
    sa.Column('research_statement', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_user_modify_info_email'), 'user_modify_info', ['email'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_user_modify_info_user_id'), 'user_modify_info', ['user_id'], unique=False, schema='tdic')
    op.create_table('workplan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('satellite', sa.String(length=10), nullable=True),
    sa.Column('production_date', sa.DateTime(), nullable=True),
    sa.Column('producer', sa.String(length=10), nullable=True),
    sa.Column('confidential_level', sa.String(length=10), nullable=True),
    sa.Column('confidential_visibility', sa.String(length=10), nullable=True),
    sa.Column('workplan_type', sa.String(levgth=10), nullable=True),
    sa.Column('wpTimeWindow_begin', sa.DateTime(), nullable=True),
    sa.Column('wpTimeWindow_end', sa.DateTime(), nullable=True),
    sa.Column('total_obs_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_table('PV',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('stp', sa.Integer(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submitter_id'], ['tdic.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_table('atel_coordinates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atel_id', sa.Integer(), nullable=True),
    sa.Column('radeg', sa.Float(), nullable=True),
    sa.Column('decdeg', sa.Float(), nullable=True),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.Column('singleclassification', sa.String(length=45), nullable=True),
    sa.Column('supernovatag', sa.Integer(), nullable=True),
    sa.Column('atelname', sa.String(length=45), nullable=True),
    sa.Column('atelurl', sa.String(length=200), nullable=True),
    sa.Column('survey', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['atel_id'], ['tdic.atel_fullcontent.atel_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_table('atel_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atel_id', sa.Integer(), nullable=True),
    sa.Column('atelname', sa.String(length=45), nullable=True),
    sa.Column('atelurl', sa.String(length=200), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['atel_id'], ['tdic.atel_fullcontent.atel_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_link', sa.String(length=300), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('submitted_time', sa.DateTime(), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submitter_id'], ['tdic.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_comment_submitted_time'), 'comment', ['submitted_time'], unique=False, schema='tdic')
    op.create_table('data_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apply_user_id', sa.Integer(), nullable=True),
    sa.Column('apply_time', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approve_time', sa.DateTime(), nullable=True),
    sa.Column('data_invalid_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apply_user_id'], ['tdic.user.id'], ),
    sa.ForeignKeyConstraint(['approver_id'], ['tdic.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('ref_link', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['tdic.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_notification_timestamp'), 'notification', ['timestamp'], unique=False, schema='tdic')
    op.create_table('observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obs_id', sa.String(length=20), nullable=False),
    sa.Column('instrument', sa.String(length=10), nullable=False),
    sa.Column('fov', sa.String(length=255), nullable=True),
    sa.Column('pnt_ra', sa.Float(), nullable=True),
    sa.Column('pnt_dec', sa.Float(), nullable=True),
    sa.Column('obj_ra', sa.Float(), nullable=False),
    sa.Column('obj_dec', sa.Float(), nullable=False),
    sa.Column('obs_start', sa.DateTime(), nullable=False),
    sa.Column('obs_end', sa.DateTime(), nullable=False),
    sa.Column('target_id', sa.String(length=20), nullable=True),
    sa.Column('object_name', sa.String(length=20), nullable=True),
    sa.Column('seqp_num', sa.Integer(), nullable=True),
    sa.Column('seg_num', sa.Integer(), nullable=True),
    sa.Column('exposure_time', sa.Float(), nullable=True),
    sa.Column('obs_type', sa.String(length=10), nullable=True),
    sa.Column('pa_pnt', sa.Float(), nullable=True),
    sa.Column('pi_id', sa.Integer(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('exposure_mode', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('archive_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pi_id'], ['tdic.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_observation_obs_id'), 'observation', ['obs_id'], unique=True, schema='tdic')
    op.create_table('observation_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workplan_id', sa.Integer(), nullable=True),
    sa.Column('obs_id', sa.String(length=20), nullable=True),
    sa.Column('obs_type', sa.String(length=10), nullable=True),
    sa.Column('obt_id', sa.Integer(), nullable=True),
    sa.Column('db_object_id', sa.String(length=35), nullable=True),
    sa.Column('obs_source_ra', sa.Float(), nullable=True),
    sa.Column('obs_source_dec', sa.Float(), nullable=True),
    sa.Column('requst_obs_duration', sa.Integer(), nullable=True),
    sa.Column('requst_obs_duration_unit', sa.String(length=10), nullable=True),
    sa.Column('wxt_cmos', sa.Integer(), nullable=True),
    sa.Column('wxt_cmos_x', sa.Float(), nullable=True),
    sa.Column('wxt_cmos_y', sa.Float(), nullable=True),
    sa.Column('time_constraints', sa.DateTime(), nullable=True),
    sa.Column('tc_programming_mode', sa.String(length=10), nullable=True),
    sa.Column('obs_start_time', sa.DateTime(), nullable=True),
    sa.Column('obs_end_time', sa.DateTime(), nullable=True),
    sa.Column('pointing_duration', sa.Float(), nullable=True),
    sa.Column('pointing_duration_unit', sa.String(length=10), nullable=True),
    sa.Column('payload_pointing_ra', sa.Float(), nullable=True),
    sa.Column('payload_pointing_dec', sa.Float(), nullable=True),
    sa.Column('quaternion_c', sa.Float(), nullable=True),
    sa.Column('quaternion_1', sa.Float(), nullable=True),
    sa.Column('quaternion_2', sa.Float(), nullable=True),
    sa.Column('quaternion_3', sa.Float(), nullable=True),
    #sa.Column('fov1', app.observation_plan.models.FOVColumn(), nullable=True),
    #sa.Column('fov2', app.observation_plan.models.FOVColumn(), nullable=True),
    #sa.Column('fov3', app.observation_plan.models.FOVColumn(), nullable=True),
    #sa.Column('fov4', app.observation_plan.models.FOVColumn(), nullable=True),
    sa.ForeignKeyConstraint(['workplan_id'], ['tdic.workplan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_module', sa.Text(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('operation_time', sa.DateTime(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['tdic.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_operation_log_operation_time'), 'operation_log', ['operation_time'], unique=False, schema='tdic')
    op.create_table('proposal_expert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('institution', sa.String(length=300), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['tdic.proposal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_proposal_expert_proposal_id'), 'proposal_expert', ['proposal_id'], unique=False, schema='tdic')
    op.create_table('proposal_investigator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=8), nullable=True),
    sa.Column('institution', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('user_group', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=25), nullable=True),
    sa.Column('country', sa.String(length=25), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('identification', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['tdic.proposal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tdic.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_proposal_investigator_email'), 'proposal_investigator', ['email'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_investigator_identification'), 'proposal_investigator', ['identification'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_investigator_name'), 'proposal_investigator', ['name'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_investigator_proposal_id'), 'proposal_investigator', ['proposal_id'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_investigator_role'), 'proposal_investigator', ['role'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_investigator_user_id'), 'proposal_investigator', ['user_id'], unique=False, schema='tdic')
    op.create_table('proposal_review_expert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('submit_status', sa.Boolean(), nullable=True),
    sa.Column('read_status', sa.Boolean(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('familiar', sa.String(length=32), nullable=True),
    sa.Column('is_sure', sa.Boolean(), nullable=True),
    sa.Column('reviewer_type', sa.String(length=32), nullable=True),
    sa.Column('review_deadline', sa.DateTime(), nullable=True),
    sa.Column('open_to_pi', sa.Boolean(), nullable=True),
    sa.Column('force_open_to_pi', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['tdic.proposal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_proposal_review_expert_email'), 'proposal_review_expert', ['email'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_review_expert_name'), 'proposal_review_expert', ['name'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_review_expert_proposal_id'), 'proposal_review_expert', ['proposal_id'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_review_expert_review_deadline'), 'proposal_review_expert', ['review_deadline'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_review_expert_reviewer_type'), 'proposal_review_expert', ['reviewer_type'], unique=False, schema='tdic')
    op.create_table('proposal_scientific_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('category_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['tdic.proposal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_proposal_scientific_category_category'), 'proposal_scientific_category', ['category'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_scientific_category_proposal_id'), 'proposal_scientific_category', ['proposal_id'], unique=False, schema='tdic')
    op.create_table('proposal_season_announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=64), nullable=True),
    sa.Column('announcement_storage_name', sa.String(length=4096), nullable=True),
    sa.Column('announcement_display_name', sa.String(length=4096), nullable=True),
    sa.Column('announcement_link', sa.Text(), nullable=True),
    sa.Column('proposal_season_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_season_id'], ['tdic.proposal_season.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_proposal_season_announcement_proposal_season_id'), 'proposal_season_announcement', ['proposal_season_id'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_season_announcement_season'), 'proposal_season_announcement', ['season'], unique=False, schema='tdic')
    op.create_table('proposal_source_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_index_in_proposal', sa.Integer(), nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=32), nullable=False),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('count_rate', sa.Float(), nullable=True),
    sa.Column('energy_upper', sa.Float(), nullable=True),
    sa.Column('energy_lower', sa.Float(), nullable=True),
    sa.Column('nh', sa.Float(), nullable=True),
    sa.Column('exposure_time', sa.Float(), nullable=True),
    sa.Column('exposure_unit', sa.String(length=10), nullable=True),
    sa.Column('multiple_observation', sa.Boolean(), nullable=True),
    sa.Column('visit_number', sa.Integer(), nullable=True),
    sa.Column('exposure_per_vist_min', sa.Float(), nullable=True),
    sa.Column('exposure_per_vist_min_unit', sa.String(length=10), nullable=True),
    sa.Column('exposure_per_vist_max', sa.Float(), nullable=True),
    sa.Column('exposure_per_vist_max_unit', sa.String(length=10), nullable=True),
    sa.Column('monitoring_cadence', sa.Integer(), nullable=True),
    sa.Column('cadence_unit', sa.String(length=10), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('precision_unit', sa.String(length=10), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('time_critical', sa.Boolean(), nullable=True),
    sa.Column('time_critical_remark', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('ant_too_trig_criteria', sa.String(length=255), nullable=True),
    sa.Column('tomm', sa.Boolean(), nullable=True),
    sa.Column('tomm_id', sa.String(length=30), nullable=True),
    sa.Colump('tomm_tile_id', sa.String(length=30), nullable=True),
    sa.Column('fxt1_obs_mode', sa.Enum('SCIENCE', 'DIAGNOSTIC', 'SAA', 'OFFSET', name='fxtobservationmode'), nullable=True),
    sa.Column('fxt1_window_mode', sa.Enum('FULLFRAME', 'PARTIALWINDOW', 'TIMING', name='fxtwindowmode'), nullable=True),
    sa.Column('fxt2_obs_mode', sa.Enum('SCIENCE', 'DIAGNOSTIC', 'SAA', 'OFFSET', name='fxtobservationmode'), nullable=True),
    sa.Column('fxt2_window_mode', sa.Enum('FULLFRAME', 'PARTIALWINDOW', 'TIMING', name='fxtwindowmode'), nullable=True),
    sa.Column('fxt1_filter', sa.Enum('CLOSEDPOSITION', 'CALIBRATIONPOSITION', 'OPENPOSITION', 'MEDIUMFILTER', 'THINFILTER', 'HOLEPOSITION', name='fxtfiltertype'), nullable=True),
    sa.Column('fxt2_filter', sa.Enum('CLOSEDPOSITION', 'CALIBRATIONPOSITION', 'OPENPOSITION', 'MEDIUMFILTER', 'THINFILTER', 'HOLEPOSITION', name='fxtfiltertype'), nullable=True),
    sa.Column('fxt_data_realtime_trans', sa.Boolean(), nullable=True),
    sa.Column('wxt_cmos', sa.String(length=4), nullable=True),
    sa.Column('wxt_config_param_switch', sa.String(length=4), nullable=True),
    sa.Column('wxt_config_force_switch', sa.String(length=4), nullable=True),
    sa.Column('wxt_operation_code_3', sa.String(length=4), nullable=True),
    sa.Column('wxt_minnsigma_dim', sa.String(length=4), nullable=True),
    sa.Column('wxt_sn_dim', sa.String(length=4), nullable=True),
    sa.Column('wxt_sn_windows', sa.String(length=4), nullable=True),
    sa.Column('wxt_retention_param_1', sa.String(length=4), nullable=True),
    sa.Column('wxt_retention_param_2', sa.String(length=4), nullable=True),
    sa.Column('wxt_retention_param_3', sa.String(length=4), nullable=True),
    sa.Column('source_priority', sa.Enum('A', 'B', 'C', 'D', name='sourcepriority'), nullable=True),
    sa.Column('wxt_x', sa.Float(), nullable=True),
    sa.Column('wxt_y', sa.Float(), nullable=True),
    sa.Column('fxt1_x', sa.Float(), nullable=True),
    sa.Column('fxt1_y', sa.Float(), nullable=True),
    sa.Column('fxt2_x', sa.Float(), nullable=True),
    sa.Column('fxt2_y', sa.Float(), nullable=True),
    sa.Column('fxt_flux', sa.Float(), nullable=True),
    sa.Column('flux_pl_index', sa.Float(), nullable=True),
    sa.Column('v_mag', sa.Float(), nullable=True),
    sa.Column('variable_source', sa.Boolean(), nullable=True),
    sa.Column('extend_source', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['tdic.proposal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_proposal_source_list_fxt1_filter'), 'proposal_source_list', ['fxt1_filter'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_source_list_fxt1_obs_mode'), 'proposal_source_list', ['fxt1_obs_mode'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_source_list_fxt1_window_mode'), 'proposal_source_list', ['fxt1_window_mode'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_source_list_fxt2_filter'), 'proposal_source_list', ['fxt2_filter'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_source_list_fxt2_obs_mode'), 'proposal_source_list', ['fxt2_obs_mode'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_source_list_fxt2_window_mode'), 'proposal_source_list', ['fxt2_window_mode'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_source_list_proposal_id'), 'proposal_source_list', ['proposal_id'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_source_list_source_name'), 'proposal_source_list', ['source_name'], unique=False, schema='tdic')
    op.create_table('proposal_technical_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('review_result', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('open_to_pi', sa.Boolean(), nullable=True),
    sa.Column('force_open_to_pi', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['tdic.proposal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_proposal_technical_review_email'), 'proposal_technical_review', ['email'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_technical_review_proposal_id'), 'proposal_technical_review', ['proposal_id'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_proposal_technical_review_review_result'), 'proposal_technical_review', ['review_result'], unique=False, schema='tdic')
    op.create_table('tdic.roles_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['tdic.permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['tdic.role.id'], )
    )
    op.create_table('smc_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('affiliation', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tdic.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_table('source_tag_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['src_id'], ['tdic.source.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tdic.source_tag.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_table('source_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('TDE', 'GRB', 'SGRB', 'LL_LGRBs', 'HL_LGRBs', 'SBO', 'HZ_GRBs', 'AGN', 'XRB', 'CV', 'STAR', 'ULX', 'MAGNETAR', 'SNR', 'GALAXY', 'UNKNOWN', 'OTHER', name='sourcetype'), nullable=True),
    sa.Column('identify_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['tdic.source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_source_type_type'), 'source_type', ['type'], unique=False, schema='tdic')
    op.create_table('stp_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('affiliation', sa.String(length=100), nullable=True),
    sa.Column('stp', sa.Text(), nullable=True),
    sa.Column('user_group', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stp_role', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tdic.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_table('user_o_auth2_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=True),
    sa.Column('token_type', sa.String(length=40), nullable=True),
    sa.Column('access_token', sa.String(length=200), nullable=True),
    sa.Column('refresh_token', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tdic.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_table('user_scientific_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tdic.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_user_scientific_category_category'), 'user_scientific_category', ['category'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_user_scientific_category_user_id'), 'user_scientific_category', ['user_id'], unique=False, schema='tdic')
    op.create_table('tdic.users_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['tdic.role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tdic.user.id'], )
    )
    op.create_table('asso_stp_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('chinese_name', sa.String(length=40), nullable=True),
    sa.Column('affiliation', sa.String(length=100), nullable=True),
    sa.Column('stp', sa.Text(), nullable=True),
    sa.Column('user_group', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('referer_user_id', sa.Integer(), nullable=True),
    sa.Column('referer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['referer_id'], ['tdic.stp_user.id'], ),
    sa.ForeignKeyConstraint(['referer_user_id'], ['tdic.user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tdic.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_table('beidou_detection',
    sa.Column('proc_ver', sa.String(length=30), nullable=True),
    sa.Column('soft_ver', sa.String(length=50), nullable=True),
    sa.Column('caldb_ver', sa.String(length=20), nullable=True),
    sa.Column('archive_time', sa.DateTime(), nullable=True),
    sa.Column('process_time', sa.DateTime(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obs_id', sa.String(length=20), nullable=True),
    sa.Column('detnam', sa.String(length=10), nullable=True),
    sa.Column('pnt_ra', sa.Float(), nullable=False),
    sa.Column('pnt_dec', sa.Float(), nullable=False),
    sa.Column('pa_pnt', sa.Float(), nullable=Truy),
    sa.Column('exposure_time', sa.Float(), nullable=True),
    #sa.Column('fov_new', app.data_center.models.FOVColumn(), nullable=True),
    sa.Column('instrument', sa.String(length=10), nullable=True),
    sa.Column('obs_start', sa.DateTime(), nullable=True),
    sa.Column('obs_end', sa.DateTime(), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=True),
    sa.Column('utcfinit', sa.Float(), nullable=True),
    sa.Column('reproc', sa.Boolean(), nullable=True),
    sa.Column('trig_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('available', 'lost', 'delete', 'suppression', name='datastatus'), nullable=True),
    sa.ForeignKeyConstraint(['obs_id'], ['tdic.observation.obs_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_beidou_detection_instrument'), 'beidou_detection', ['instrument'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_beidou_detection_obs_end'), 'beidou_detection', ['obs_end'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_beidou_detection_obs_start'), 'beidou_detection', ['obs_start'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_beidou_detection_status'), 'beidou_detection', ['status'], ynique=False, schema='tdic')
    op.create_table('comment_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('response_content', sa.Text(), nullable=False),
    sa.Column('responser_id', sa.Integer(), nullable=True),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.Column('check_status', sa.String(length=30), nullable=True),
    sa.Column('checker_id', sa.Integer(), nullable=True),
    sa.Column('check_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checker_id'], ['tdic.user.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['tdic.comment.id'], ),
    sa.ForeignKeyConstraint(['responser_id'], ['tdic.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_comment_response_response_date'), 'comment_response', ['response_date'], unique=False, schema='tdic')
    op.create_table('fxt_detection',
    sa.Column('proc_ver', sa.String(length=30), nullable=True),
    sa.Column('soft_ver', sa.String(length=50), nullable=True),
    sa.Column('caldb_ver', sa.String(length=20), nullable=True),
    sa.Column('archive_time', sa.DateTime(), nullable=True),
    sa.Column('process_time', sa.DateTime(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obs_id', sa.String(length=20), nullable=True),
    sa.Column('detnam', sa.String(length=10), nullable=True),
    sa.Column('obs_mode', sa.String(length=10), nullable=True),
    sa.Column('object_name', sa.String(length=25), nullable=True),
    sa.Column('obj_ra', sa.Float(), nullable=False),
    sa.Column('obj_dec', sa.Float(), nullable=False),
    sa.Column('pnt_ra', sa.Float(), nullable=False),
    sa.Column('pnt_dec', sa.Float(), nullable=False),
    sa.Column('exposure_time', sa.Float(), nullable=True),
    #sa.Column('fov_new', app.data_center.models.FOVColumn(), nullable=True),
    sa.Column('instrument', sa.String(length=10), nullable=True),
    sa.Column('obs_start', sa.DateTibe(), nullable=True),
    sa.Column('obs_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('available', 'lost', 'delete', 'suppression', name='datastatus'), nullable=True),
    sa.Column('data_mode', sa.String(length=10), nullable=True),
    sa.Column('observer', sa.String(length=10), nullable=True),
    sa.Column('latest', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['obs_id'], ['tdic.observation.obs_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_fxt_detection_data_mode'), 'fxt_detection', ['data_mode'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_fxt_detection_instrument'), 'fxt_detection', ['instrument'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_fxt_detection_obs_end'), 'fxt_detection', ['obs_end'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_fxt_detection_obs_start'), 'fxt_detection', ['obs_start'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_fxt_detection_observer'), 'fxt_detection', ['observer'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_fxt_detection_status'), 'fxt_detection', ['status'], unique=False, schema='tdic')
    op.create_table('wxt_detection',
    sa.Column('proc_ver', sa.String(length=30), nullable=True),
    sa.Column('soft_ver', sa.String(length=50), nullable=True),
    sa.Column('caldb_ver', sa.String(length=20), nullable=True),
    sa.Column('archive_time', sa.DateTime(), nullable=True),
    sa.Column('process_time', sa.DateTime(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obs_id', sa.String(length=20), nullable=True),
    sa.Column('detnam', sa.String(length=10), nullable=True),
    sa.Column('pnt_ra', sa.Float(), nullable=False),
    sa.Column('pnt_dec', sa.Float(), nullable=False),
    sa.Column('pa_pnt', sa.Float(), nullable=True),
    sa.Column('exposure_time', sa.Float(), nullable=True),
    #sa.Column('fov_new', app.data_center.models.FOVColumn(), nullable=True),
    sa.Column('instrument', sa.String(length=10), nullable=True),
    sa.Column('obs_start', sa.DateTime(), nullable=True),
    sa.Column('obs_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('available', 'lost', 'delete', 'suppression', name='datastatus'), nullable=True),
    sa.Column('trigger', sa.String(length=10), nullable=True),
    sa.Column('trig_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['obs_id'], ['tdic.observation.obs_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_wxt_detection_instrument'), 'wxt_detection', ['instrument'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_wxt_detection_obs_end'), 'wxt_detection', ['obs_end'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_wxt_detection_obs_id'), 'wxt_detection', ['obs_id'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_wxt_detection_obs_start'), 'wxt_detection', ['obs_start'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_wxt_detection_status'), 'wxt_detection', ['status'], unique=False, schema='tdic')
    op.create_table('beidou_source_observation',
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('detnam', sa.String(length=10), nullable=True),
    sa.Column('index_in_det', sa.Integer(), nullable=True),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.Column('pos_err', sa.Float(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('qparam', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('var', sa.Float(), nullable=True),
    sa.Column('net_rate', sa.Float(), nullable=True),
    sa.Column('hr', sa.Float(), nullable=True),
    sa.Column('src_significance', sa.Float(), nullable=True),
    sa.Column('src_code', sa.ARRAY(sa.Boolean()), nullable=True),
    sa.Column('rank', sa.ARRAY(sa.Boolean()), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['tdic.beidou_detection.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['tdic.source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_beidou_source_observation_detection_id'), 'beidou_source_observation', ['detection_id'], unique=False, schema='tdic')
    op.create_index(op.f('ix_tdic_beidou_source_observation_source_id'), 'beidou_source_observation', ['source_id'], unique=False, schema='tdic')
    op.create_table('tdic.detection_application',
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['tdic.data_application.id'], ),
    sa.ForeignKeyConstraint(['detection_id'], ['tdic.wxt_detection.id'], )
    )
    op.create_table('fxt_data_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obs_id', sa.String(length=20), nullable=True),
    sa.Column('detnam', sa.String(length=10), nullable=True),
    sa.Column('obs_mode', sa.String(length=10), nullable=True),
    sa.Column('data_mode', sa.String(length=10), nullable=True),
    sa.Column('hl_latest_version', sa.String(length=10), nullable=True),
    sa.Column('ql_latest_version', sa.String(length=10), nullable=True),
    sa.Column('fxtdetection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fxtdetection_id'], ['tdic.fxt_detection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obs_id', 'detnam'),
    schema='tdic'
    )
    op.create_table('fxt_source_observation',
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('fxt_detection_id', sa.Integer(), nullable=True),
    sa.Column('detnam', sa.String(length=10), nullable=True),
    sa.Column('obs_mode', sa.String(length=10), nullable=True),
    sa.Column('target_name', sa.String(length=25), nullable=True),
    sa.Column('ra_target', sa.Float(), nullable=True),
    sa.Column('dec_target', sa.Float(), nullable=True),
    sa.Column('offset_target', sa.Float(), nullable=True),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.Column('ra_err', sa.Float(), nullable=True),
    sa.Column('dec_err', sa.Float(), nullable=True),
    sa.Column('ra_match', sa.Float(), nullable=True),
    sa.Column('dec_match', sa.Float(), nullable=True),
    sa.Column('name_match', sa.String(length=25), nullable=True),
    sa.Column('flux_match', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('rate_err', sa.Float(), nullable=True),
    sa.Column('flux', sa.Float(), nullable=True),
    sa.Column('flux_err', sa.Float(), nullable=True),
    sa.Column('snr', sa.Float(), nullable=True),
    sa.Column('flux_delta', sa.Float(), nullable=True),
    sa.Column('hardness', sa.Float(), nullable=True),
    sa.Column('index_in_det', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fxt_detection_id'], ['tdic.fxt_detection.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['tdic.source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_fxt_source_observation_fxt_detection_id'), 'fxt_source_observation', ['fxt_detection_id'], unique=False, schema='tdic')
    op.create_table('source_observation',
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('wxt_detection_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('x_err', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('y_err', sa.Float(), nullable=True),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.Column('pos_err', sa.Float(), nullable=True),
    sa.Column('npix_source', sa.Integer(), nullable=True),
    sa.Column('detnam', sa.String(length=10), nullable=True),
    sa.Column('index_in_det', sa.Integer(), nullable=True),
    sa.Column('net_counts', sa.Float(), nullable=True),
    sa.Column('bkg_counts', sa.Float(), nullable=True),
    sa.Column('net_rate', sa.Float(), nullable=True),
    sa.Column('exp_time', sa.Float(), nullable=True),
    sa.Column('src_significance', sa.Float(), nullable=True),
    sa.Column('class_star', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('light_curve', sa.String(length=255), nullable=True),
    sa.Column('spectrum', sa.String(length=255), nullable=True),
    sa.Column('elongation', sa.Float(), nullable=True),
    sa.Column('transient_candidate', sa.Boolean(), nullable=True),
    sa.Column('xray_counterpart', sa.Text(), nullable=True),
    sa.Column('other_counterpart', sa.Text(), nullable=True),
    sa.Column('upperlimit', sa.Text(), nullable=True),
    sa.Column('ref_ra', sa.Float(), nullable=True),
    sa.Column('ref_dec', sa.Float(), nullable=True),
    sa.Column('ref_sep', sa.Float(), nullable=True),
    sa.Column('ai_classification', sa.String(length=60), nullable=True),
    sa.Column('ai_prob', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['tdic.source.id'], ),
    sa.ForeignKeyConstraint(['wxt_detection_id'], ['tdic.wxt_detection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wxt_detection_id', 'source_id'),
    schema='tdic'
    )
    op.create_index(op.f('ix_tdic_source_observation_wxt_detection_id'), 'source_observation', ['wxt_detection_id'], unique=False, schema='tdic')
    op.create_table('wxt_data_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obs_id', sa.String(length=20), nullable=True),
    sa.Column('detnam', sa.String(length=10), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['tdic.wxt_detection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obs_id', 'detnam'),
    schema='tdic'
    )
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('src_obs_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['src_obs_id'], ['tdic.source_observation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    op.create_table('ta_comment_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_type', sa.String(length=20), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('simbad_name', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('ref_flux', sa.Float(), nullable=True),
    sa.Column('ta_id', sa.Integer(), nullable=True),
    sa.Column('src_id', sa.Integer(), nullable=True),
    sa.Column('bd_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bd_id'], ['tdic.beidou_source_observation.id'], ),
    sa.ForeignKeyConstraint(['src_id'], ['tdic.source_observation.id'], ),
    sa.ForeignKeyConstraint(['ta_id'], ['tdic.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tdic'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ta_comment_record', schema='tdic')
    op.drop_table('issue', schema='tdic')
    op.drop_table('wxt_data_version', schema='tdic')
    op.drop_index(op.f('ix_tdic_source_observation_wxt_detection_id'), table_name='source_observation', schema='tdic')
    op.drop_table('source_observation', schema='tdic')
    op.drop_index(op.f('ix_tdic_fxt_source_observation_fxt_detection_id'), table_name='fxt_source_observation', schema='tdic')
    op.drop_table('fxt_source_observation', schema='tdic')
    op.drop_table('fxt_data_version', schema='tdic')
    op.drop_table('tdic.detection_application')
    op.drop_index(op.f('ix_tdic_beidou_source_observation_source_id'), table_name='beidou_source_observation', schema='tdic')
    op.drop_index(op.f('ix_tdic_beidou_source_observation_detection_id'), table_name='beidou_source_observation', schema='tdic')
    op.drop_table('beidou_source_observation', schema='tdic')
    op.drop_index(op.f('ix_tdic_wxt_detection_status'), table_name='wxt_detection', schema='tdic')
    op.drop_index(op.f('ix_tdic_wxt_detection_obs_start'), table_name='wxt_detection', schema='tdic')
    op.drop_index(op.f('ix_tdic_wxt_detection_obs_id'), table_name='wxt_detection', schema='tdic')
    op.drop_index(op.f('ix_tdic_wxt_detection_obs_end'), table_name='wxt_detection', schema='tdic')
    op.drop_index(op.f('ix_tdic_wxt_detection_instrument'), table_name='wxt_detection', schema='tdic')
    op.drop_table('wxt_detection', schema='tdic')
    op.drop_index(op.f('ix_tdic_fxt_detection_status'), table_name='fxt_detection', schema='tdic')
    op.drop_index(op.f('ix_tdic_fxt_detection_observer'), table_name='fxt_detection', schema='tdic')
    op.drop_index(op.f('ix_tdic_fxt_detection_obs_start'), table_name='fxt_detection', schema='tdic')
    op.drop_index(op.f('ix_tdic_fxt_detection_obs_end'), table_name='fxt_detection', schema='tdic')
    op.drop_index(op.f('ix_tdic_fxt_detection_instrument'), table_name='fxt_detection', schema='tdic')
    op.drop_index(op.f('ix_tdic_fxt_detection_data_mode'), table_name='fxt_detection', schema='tdic')
    op.drop_table('fxt_detection', schema='tdic')
    op.drop_index(op.f('ix_tdic_comment_response_response_date'), table_name='comment_response', schema='tdic')
    op.drop_table('comment_response', schema='tdic')
    op.drop_index(op.f('ix_tdic_beidou_detection_status'), table_name='beidou_detection', schema='tdic')
    op.drop_index(op.f('ix_tdic_beidou_detection_obs_start'), table_name='beidou_detection', schema='tdic')
    op.drop_index(op.f('ix_tdic_beidou_detection_obs_end'), table_name='beidou_detection', schema='tdic')
    op.drop_index(op.f('ix_tdic_beidou_detection_instrument'), table_name='beidou_detection', schema='tdic')
    op.drop_table('beidou_detection', schema='tdic')
    op.drop_table('asso_stp_user', schema='tdic')
    op.drop_table('tdic.users_roles')
    op.drop_index(op.f('ix_tdic_user_scientific_category_user_id'), table_name='user_scientific_category', schema='tdic')
    op.drop_index(op.f('ix_tdic_user_scientific_category_category'), table_name='user_scientific_category', schema='tdic')
    op.drop_table('user_scientific_category', schema='tdic')
    op.drop_table('user_o_auth2_token', schema='tdic')
    op.drop_table('stp_user', schema='tdic')
    op.drop_index(op.f('ix_tdic_source_type_type'), table_name='source_type', schema='tdic')
    op.drop_table('source_type', schema='tdic')
    op.drop_table('source_tag_relationship', schema='tdic')
    op.drop_table('smc_user', schema='tdic')
    op.drop_table('tdic.roles_permissions')
    op.drop_index(op.f('ix_tdic_proposal_technical_review_review_result'), table_name='proposal_technical_review', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_technical_review_proposal_id'), table_name='proposal_technical_review', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_technical_review_email'), table_name='proposal_technical_review', schema='tdic')
    op.drop_table('proposal_technical_review', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_source_list_source_name'), table_name='proposal_source_list', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_source_list_proposal_id'), table_name='proposal_source_list', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_source_list_fxt2_window_mode'), table_name='proposal_source_list', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_source_list_fxt2_obs_mode'), table_name='proposal_source_list', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_source_list_fxt2_filter'), table_name='proposal_source_list', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_source_list_fxt1_window_mode'), table_name='proposal_source_list', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_source_list_fxt1_obs_mode'), table_name='proposal_source_list', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_source_list_fxt1_filter'), table_name='proposal_source_list', schema='tdic')
    op.drop_table('proposal_source_list', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_season_announcement_season'), table_name='proposal_season_announcement', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_season_announcement_proposal_season_id'), table_name='proposal_season_announcement', schema='tdic')
    op.drop_table('proposal_season_announcement', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_scientific_category_proposal_id'), table_name='proposal_scientific_category', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_scientific_category_category'), table_name='proposal_scientific_category', schema='tdic')
    op.drop_table('proposal_scientific_category', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_review_expert_reviewer_type'), table_name='proposal_review_expert', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_review_expert_review_deadline'), table_name='proposal_review_expert', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_review_expert_proposal_id'), table_name='proposal_review_expert', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_review_expert_name'), table_name='proposal_review_expert', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_review_expert_email'), table_name='proposal_review_expert', schema='tdic')
    op.drop_table('proposal_review_expert', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_investigator_user_id'), table_name='proposal_investigator', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_investigator_role'), table_name='proposal_investigator', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_investigator_proposal_id'), table_name='proposal_investigator', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_investigator_name'), table_name='proposal_investigator', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_investigator_identification'), table_name='proposal_investigator', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_investigator_email'), table_name='proposal_investigator', schema='tdic')
    op.drop_table('proposal_investigator', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_expert_proposal_id'), table_name='proposal_expert', schema='tdic')
    op.drop_table('proposal_expert', schema='tdic')
    op.drop_index(op.f('ix_tdic_operation_log_operation_time'), table_name='operation_log', schema='tdic')
    op.drop_table('operation_log', schema='tdic')
    op.drop_table('observation_plan', schema='tdic')
    op.drop_index(op.f('ix_tdic_observation_obs_id'), table_name='observation', schema='tdic')
    op.drop_table('observation', schema='tdic')
    op.drop_index(op.f('ix_tdic_notification_timestamp'), table_name='notification', schema='tdic')
    op.drop_table('notification', schema='tdic')
    op.drop_table('data_application', schema='tdic')
    op.drop_index(op.f('ix_tdic_comment_submitted_time'), table_name='comment', schema='tdic')
    op.drop_table('comment', schema='tdic')
7   op.drop_table('atel_names', schema='tdic')
    op.drop_table('atel_coordinates', schema='tdic')
    op.drop_table('PV', schema='tdic')
    op.drop_table('workplan', schema='tdic')
    op.drop_index(op.f('ix_tdic_user_modify_info_user_id'), table_name='user_modify_info', schema='tdic')
    op.drop_index(op.f('ix_tdic_user_modify_info_email'), table_name='user_modify_info', schema='tdic')
    op.drop_table('user_modify_info', schema='tdic')
    op.drop_index(op.f('ix_tdic_user_id_weibo'), table_name='user', schema='tdic')
    op.drop_index(op.f('ix_tdic_user_id_wechat'), table_name='user', schema='tdic')
    op.drop_index(op.f('ix_tdic_user_id_qq'), table_name='user', schema='tdic')
    op.drop_index(op.f('ix_tdic_user_id_github'), table_name='user', schema='tdic')
    op.drop_index(op.f('ix_tdic_user_id_escience'), table_name='user', schema='tdic')
    op.drop_index(op.f('ix_tdic_user_id_cstnet'), table_name='user', schema='tdic')
    op.drop_index(op.f('ix_tdic_user_email'), table_name='user', schema='tdic')
    op.drop_table('user', schema='tdic')
    op.drop_index(op.f('ix_tdic_sys_menu_url'), table_name='sys_menu', schema='tdic')
    op.drop_index(op.f('ix_tdic_sys_menu_title_zh'), table_name='sys_menu', schema='tdic')
    op.drop_index(op.f('ix_tdic_sys_menu_title_en'), table_name='sys_menu', schema='tdic')
    op.drop_index(op.f('ix_tdic_sys_menu_order'), table_name='sys_menu', schema='tdic')
    op.drop_table('sys_menu', schema='tdic')
    op.drop_table('sql_alchemy_task', schema='tdic')
    op.drop_table('source_tag', schema='tdic')
    op.drop_index(op.f('ix_tdic_source_type'), table_name='source', schema='tdic')
    op.drop_table('source', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_survey_title'), table_name='science_team_survey', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_survey_telephone'), table_name='science_team_survey', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_survey_reseach_type'), table_name='science_team_survey', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_survey_observation_research'), table_name='science_team_survey', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_survey_name'), table_name='science_team_survey', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_survey_institute'), table_name='science_team_survey', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_survey_how_to_analyze_data'), table_name='science_team_survey', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_survey_email'), table_name='science_team_survey', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_survey_address'), table_name='science_team_survey', schema='tdic')
    op.drop_table('science_team_survey', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_application_title'), table_name='science_team_application', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_application_telephone'), table_name='science_team_application', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_application_reseach_type'), table_name='science_team_application', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_application_observation_research'), table_name='science_team_application', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_application_name'), table_name='science_team_application', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_application_institute'), table_name='science_team_application', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_application_email'), table_name='science_team_application', schema='tdic')
    op.drop_index(op.f('ix_tdic_science_team_application_address'), table_name='science_team_application', schema='tdic')
    op.drop_table('science_team_application', schema='tdic')
    op.drop_table('role', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_season_season'), table_name='proposal_season', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_season_review_deadline'), table_name='proposal_season', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_season_open_date'), table_name='proposal_season', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_season_identification'), table_name='proposal_season', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_season_expiration'), table_name='proposal_season', schema='tdic')
    op.drop_table('proposal_season', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_type2'), table_name='proposal', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_type1'), table_name='proposal', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_stp'), table_name='proposal', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_season'), table_name='proposal', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_proposal_season_id'), table_name='proposal', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_proposal_number'), table_name='proposal', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_priority'), table_name='proposal', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_pid'), table_name='proposal', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_identification'), table_name='proposal', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_expiration'), table_name='proposal', schema='tdic')
    op.drop_index(op.f('ix_tdic_proposal_code'), table_name='proposal', schema='tdic')
    op.drop_table('proposal', schema='tdic')
    op.drop_table('permission', schema='tdic')
    op.drop_index(op.f('ix_tdic_paper_user_id'), table_name='paper', schema='tdic')
    op.drop_table('paper', schema='tdic')
    op.drop_table('login_session', schema='tdic')
    op.drop_index(op.f('ix_tdic_friend_link_url'), table_name='friend_link', schema='tdic')
    op.drop_index(op.f('ix_tdic_friend_link_name_zh'), table_name='friend_link', schema='tdic')
    op.drop_index(op.f('ix_tdic_friend_link_name_en'), table_name='friend_link', schema='tdic')
    op.drop_index(op.f('ix_tdic_friend_link_logo_url'), table_name='friend_link', schema='tdic')
    op.drop_table('friend_link', schema='tdic')
    op.drop_table('atel_fullcontent', schema='tdic')
    op.drop_index(op.f('ix_tdic_associate_science_team_application_referer_name'), table_name='associate_science_team_application', schema='tdic')
    op.drop_table('associate_science_team_application', schema='tdic')
    op.drop_table('pipeline')
    op.drop_index(op.f('ix_login_tries_email'), table_name='login_tries')
    op.drop_table('login_tries')
    op.drop_index(op.f('ix_cms_category_name'), table_name='cms_category')
    op.drop_index(op.f('ix_cms_category_category_type'), table_name='cms_category')
    op.drop_table('cms_category')
    op.drop_index(op.f('ix_cms_carousel_title'), table_name='cms_carousel')
    op.drop_table('cms_carousel')
    op.drop_index(op.f('ix_cms_article_title'), table_name='cms_article')
    op.drop_index(op.f('ix_cms_article_article_type'), table_name='cms_article')
    op.drop_table('cms_article')
    op.drop_table('catalogue_metadata')
    op.drop_table('SNAlert')
    op.drop_table('GWAlert')
    op.drop_table('GRBAlert')
    # ### end Alembic commands ###
